name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "cython<3.0" buildozer

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libltdl-dev ffmpeg libsdl2-dev openjdk-17-jdk

    - name: Pre-accept Android SDK Licenses
      run: |
        mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
        echo -e "\n89330d22263015a00268a31bc008649a93368390\nd56f5187479451eabf01fb78af6dfcb131a6481e\n24333f8a6371b6a4d16173f9a931657f7b301192" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
        echo -e "\n84831b9402116da57d5a44efc11a43ed2942c492" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-preview-license

    - name: Build with Buildozer
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: antrax-apk
        path: bin/*.apk
